import json
import subprocess
from pathlib import Path

from graphics import render_graphic


# =========================================================
# PROJECT CONFIG
# =========================================================

ROOT = Path(".").resolve()

TIMELINE = ROOT / "timeline" / "reel_01.json"
OUTPUT = ROOT / "reel_01_test.mp4"
WORK = ROOT / "render_work"

W = 1080
H = 1920
FPS = 30

VIDEO_CODEC = "libx264"
PRESET = "veryfast"
PIX_FMT = "yuv420p"

AUDIO_CODEC = "aac"
AUDIO_BITRATE = "192k"

WORK.mkdir(parents=True, exist_ok=True)


# =========================================================
# COMMAND RUNNER
# =========================================================

def run(cmd):
    print("\nRUNNING:")
    print(" ".join(str(x) for x in cmd))

    subprocess.run(
        [str(x) for x in cmd],
        check=True
    )


# =========================================================
# FFPROBE HELPERS
# =========================================================

def get_duration(file):
    result = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            str(file),
        ],
        capture_output=True,
        text=True,
        check=True,
    )

    value = result.stdout.strip()

    if not value:
        raise RuntimeError(
            f"Could not determine duration: {file}"
        )

    return float(value)


def has_audio(file):
    result = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-select_streams",
            "a",
            "-show_entries",
            "stream=index",
            "-of",
            "csv=p=0",
            str(file),
        ],
        capture_output=True,
        text=True,
    )

    return bool(result.stdout.strip())


# =========================================================
# PRESENTER ASSET FINDER
# =========================================================

def find_presenter_asset(asset_path):
    """
    Finds presenter assets even if the actual filename
    contains spaces.

    Examples:

        gen1.mp4
        gen 1.mp4

        gen2.mp4
        gen 2.mp4

        gen3.mp4
        gen 3.mp4
    """

    requested = ROOT / asset_path

    # Exact path
    if requested.exists():
        return requested

    filename = requested.name

    alternatives = {
        "gen1.mp4": "gen 1.mp4",
        "gen2.mp4": "gen 2.mp4",
        "gen3.mp4": "gen 3.mp4",
        "gen4.mp4": "gen 4.mp4",
    }

    if filename in alternatives:

        alternative = (
            requested.parent /
            alternatives[filename]
        )

        if alternative.exists():
            return alternative

    # Reverse lookup:
    # If JSON says "gen 1.mp4" but actual file is gen1.mp4
    reverse_alternatives = {
        "gen 1.mp4": "gen1.mp4",
        "gen 2.mp4": "gen2.mp4",
        "gen 3.mp4": "gen3.mp4",
        "gen 4.mp4": "gen4.mp4",
    }

    if filename in reverse_alternatives:

        alternative = (
            requested.parent /
            reverse_alternatives[filename]
        )

        if alternative.exists():
            return alternative

    return None


# =========================================================
# NORMALIZE PRESENTER VIDEO
# =========================================================

def render_presenter(output, source, duration):
    """
    Converts presenter footage into the standard project format:

    1080x1920
    30 FPS
    H.264
    AAC
    yuv420p

    Original presenter audio is preserved.
    """

    run(
        [
            "ffmpeg",
            "-y",

            "-i",
            str(source),

            "-t",
            str(duration),

            "-vf",
            (
                f"scale={W}:{H}:"
                "force_original_aspect_ratio=increase,"
                f"crop={W}:{H},"
                "setsar=1"
            ),

            "-r",
            str(FPS),

            "-c:v",
            VIDEO_CODEC,

            "-preset",
            PRESET,

            "-pix_fmt",
            PIX_FMT,

            "-c:a",
            AUDIO_CODEC,

            "-b:a",
            AUDIO_BITRATE,

            "-ar",
            "48000",

            "-ac",
            "2",

            "-shortest",

            str(output),
        ]
    )


# =========================================================
# ADD SILENT AUDIO TO GRAPHIC
# =========================================================

def add_silent_audio(output, video_file, duration):
    """
    Graphics generated by graphics.py normally have video only.

    This function adds silent stereo AAC audio so every shot
    has identical video/audio stream structure.

    This makes concat much safer.
    """

    run(
        [
            "ffmpeg",
            "-y",

            "-i",
            str(video_file),

            "-f",
            "lavfi",

            "-i",
            "anullsrc=channel_layout=stereo:sample_rate=48000",

            "-t",
            str(duration),

            "-map",
            "0:v:0",

            "-map",
            "1:a:0",

            "-c:v",
            "libx264",

            "-preset",
            PRESET,

            "-pix_fmt",
            PIX_FMT,

            "-c:a",
            AUDIO_CODEC,

            "-b:a",
            AUDIO_BITRATE,

            "-ar",
            "48000",

            "-ac",
            "2",

            "-shortest",

            str(output),
        ]
    )


# =========================================================
# PLACEHOLDER
# =========================================================

def render_placeholder(output, duration, text):
    """
    Emergency fallback.

    This prevents the whole render from crashing when a
    graphic asset is not available yet.
    """

    safe_text = (
        str(text)
        .replace("\\", "")
        .replace("'", "\\'")
        .replace(":", "\\:")
    )

    temporary = WORK / (
        f"_placeholder_{output.stem}.mp4"
    )

    run(
        [
            "ffmpeg",
            "-y",

            "-f",
            "lavfi",

            "-i",
            (
                f"color=c=black:"
                f"s={W}x{H}:"
                f"r={FPS}:"
                f"d={duration}"
            ),

            "-vf",
            (
                "drawtext="
                "fontfile=/usr/share/fonts/"
                "truetype/dejavu/"
                "DejaVuSans-Bold.ttf:"
                f"text='{safe_text}':"
                "fontcolor=white:"
                "fontsize=70:"
                "x=(w-text_w)/2:"
                "y=(h-text_h)/2"
            ),

            "-c:v",
            VIDEO_CODEC,

            "-preset",
            PRESET,

            "-pix_fmt",
            PIX_FMT,

            "-an",

            str(temporary),
        ]
    )

    add_silent_audio(
        output,
        temporary,
        duration
    )

    if temporary.exists():
        temporary.unlink()


# =========================================================
# NORMALIZE GRAPHIC
# =========================================================

def render_graphic_shot(output, shot):
    """
    Calls graphics.py and then adds silent audio.
    """

    duration = float(shot["duration"])

    temporary = WORK / (
        f"_graphic_{shot['id']:02d}.mp4"
    )

    try:

        render_graphic(
            temporary,
            shot
        )

        if not temporary.exists():
            raise RuntimeError(
                f"graphics.py did not create: {temporary}"
            )

        add_silent_audio(
            output,
            temporary,
            duration
        )

        temporary.unlink()

    except Exception as error:

        print()
        print(
            f"WARNING: Graphic Shot "
            f"{shot['id']} failed."
        )

        print(
            f"Reason: {error}"
        )

        print(
            "Using emergency placeholder."
        )

        if temporary.exists():
            temporary.unlink()

        render_placeholder(
            output,
            duration,
            f"SHOT {shot['id']} — GRAPHIC"
        )


# =========================================================
# LOAD TIMELINE
# =========================================================

if not TIMELINE.exists():

    raise FileNotFoundError(
        f"Timeline not found: {TIMELINE}"
    )


with open(
    TIMELINE,
    "r",
    encoding="utf-8"
) as f:

    timeline = json.load(f)


shots = timeline.get("shots", [])

if not shots:

    raise RuntimeError(
        "Timeline contains no shots."
    )


print()
print("=" * 70)
print("REEL FACTORY")
print("=" * 70)

print(
    f"Project: {timeline.get('project', 'unknown')}"
)

print(
    f"Resolution: {W}x{H}"
)

print(
    f"FPS: {FPS}"
)

print(
    f"Shots: {len(shots)}"
)

print("=" * 70)


# =========================================================
# RENDER ALL SHOTS
# =========================================================

rendered_shots = []


for shot in shots:

    shot_id = int(shot["id"])
    duration = float(shot["duration"])
    shot_type = shot["type"]

    output = (
        WORK /
        f"shot_{shot_id:02d}.mp4"
    )

    print()
    print("=" * 70)

    print(
        f"SHOT {shot_id} | "
        f"TYPE={shot_type} | "
        f"DURATION={duration}s"
    )

    print("=" * 70)


    # -----------------------------------------------------
    # PRESENTER
    # -----------------------------------------------------

    if shot_type == "presenter":

        asset_path = shot.get("asset")

        if not asset_path:

            print(
                "WARNING: No presenter asset specified."
            )

            render_placeholder(
                output,
                duration,
                f"SHOT {shot_id} — PRESENTER"
            )

        else:

            source = find_presenter_asset(
                asset_path
            )

            if source is None:

                print(
                    "WARNING: Presenter asset not found:"
                )

                print(
                    f"  Requested: {asset_path}"
                )

                print(
                    "Creating fallback placeholder."
                )

                render_placeholder(
                    output,
                    duration,
                    f"SHOT {shot_id} — PRESENTER"
                )

            else:

                print(
                    f"Presenter asset: {source}"
                )

                render_presenter(
                    output,
                    source,
                    duration
                )


    # -----------------------------------------------------
    # GRAPHIC
    # -----------------------------------------------------

    else:

        render_graphic_shot(
            output,
            shot
        )


    # -----------------------------------------------------
    # VERIFY SHOT
    # -----------------------------------------------------

    if not output.exists():

        raise RuntimeError(
            f"Shot was not created: {output}"
        )

    if output.stat().st_size == 0:

        raise RuntimeError(
            f"Shot is empty: {output}"
        )

    shot_duration = get_duration(
        output
    )

    print(
        f"Rendered successfully: "
        f"{shot_duration:.2f}s"
    )

    print(
        f"Audio stream: "
        f"{'YES' if has_audio(output) else 'NO'}"
    )

    rendered_shots.append(output)


# =========================================================
# CREATE CONCAT FILE
# =========================================================

concat_file = (
    WORK /
    "concat.txt"
)


with open(
    concat_file,
    "w",
    encoding="utf-8"
) as f:

    for clip in rendered_shots:

        f.write(
            f"file '{clip.resolve()}'\n"
        )


print()
print("=" * 70)
print("CONCAT FILE CREATED")
print("=" * 70)

print(concat_file)


# =========================================================
# FINAL ASSEMBLY
# =========================================================

print()
print("=" * 70)
print("ASSEMBLING FINAL REEL")
print("=" * 70)


run(
    [
        "ffmpeg",
        "-y",

        "-f",
        "concat",

        "-safe",
        "0",

        "-i",
        str(concat_file),

        "-c:v",
        VIDEO_CODEC,

        "-preset",
        PRESET,

        "-pix_fmt",
        PIX_FMT,

        "-c:a",
        AUDIO_CODEC,

        "-b:a",
        AUDIO_BITRATE,

        "-ar",
        "48000",

        "-ac",
        "2",

        str(OUTPUT),
    ]
)


# =========================================================
# FINAL VERIFICATION
# =========================================================

if not OUTPUT.exists():

    raise RuntimeError(
        "Final reel was not created."
    )


if OUTPUT.stat().st_size == 0:

    raise RuntimeError(
        "Final reel exists but is empty."
    )


final_duration = get_duration(
    OUTPUT
)


print()
print("=" * 70)
print("REEL FACTORY TEST RENDER COMPLETE")
print("=" * 70)

print(
    f"OUTPUT: {OUTPUT}"
)

print(
    f"SIZE: "
    f"{OUTPUT.stat().st_size / 1024:.1f} KB"
)

print(
    f"DURATION: "
    f"{final_duration:.2f}s"
)

print(
    f"AUDIO: "
    f"{'YES' if has_audio(OUTPUT) else 'NO'}"
)

print("=" * 70)
print("SUCCESS")
print("=" * 70)
